export {default as LoginForm } from './forms/authentication/LoginForm.svelte'
export {default as SignUpForm } from './forms/authentication/SignUpForm.svelte'
export {default as PasswordResetForm } from './forms/authentication/PasswordResetForm.svelte'
export {default as PatientForm } from './forms/patients/PatientForm.svelte'
export { patients } from './stores/PatientStore'
export { user } from './stores/UserStore'
export { supabase } from './stores/supabaseClient'

// export {default as SignUpForm } from './forms/authentication/SignUpForm.svelte'
// export {default as SignUpForm } from './forms/authentication/SignUpForm.svelte'