// This file has been automatically generated by `objc2`'s `header-translator`.
// DO NOT EDIT

#![allow(unused_imports)]
#![allow(deprecated)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(missing_docs)]
#![allow(clippy::too_many_arguments)]
#![allow(clippy::type_complexity)]
#![allow(clippy::upper_case_acronyms)]
#![allow(clippy::identity_op)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::doc_lazy_continuation)]
#![allow(rustdoc::broken_intra_doc_links)]
#![allow(rustdoc::bare_urls)]
#![allow(rustdoc::unportable_markdown)]
#![allow(rustdoc::invalid_html_tags)]

#[link(name = "ImageCaptureCore", kind = "framework")]
extern "C" {}


#[path = "ICDevice.rs"]
mod __ICDevice;

#[path = "ICDeviceBrowser.rs"]
mod __ICDeviceBrowser;

#[path = "ICScannerBandData.rs"]
mod __ICScannerBandData;

#[path = "ICScannerDevice.rs"]
mod __ICScannerDevice;

#[path = "ICScannerFunctionalUnits.rs"]
mod __ICScannerFunctionalUnits;

#[path = "ImageCaptureConstants.rs"]
mod __ImageCaptureConstants;

#[path = "ImageCapturePlatform.rs"]
mod __ImageCapturePlatform;

pub use self::__ICDevice::ICDevice;

pub use self::__ICDevice::ICDeviceCanEjectOrDisconnect;

pub use self::__ICDevice::ICDeviceCapability;

pub use self::__ICDevice::ICDeviceDelegate;

pub use self::__ICDevice::ICDeviceLocationDescriptionBluetooth;

pub use self::__ICDevice::ICDeviceLocationDescriptionFireWire;

pub use self::__ICDevice::ICDeviceLocationDescriptionMassStorage;

pub use self::__ICDevice::ICDeviceLocationDescriptionUSB;

pub use self::__ICDevice::ICDeviceLocationOptions;

pub use self::__ICDevice::ICDeviceLocationType;

pub use self::__ICDevice::ICDeviceLocationTypeMask;

pub use self::__ICDevice::ICDeviceStatus;

pub use self::__ICDevice::ICDeviceTransport;

pub use self::__ICDevice::ICDeviceType;

pub use self::__ICDevice::ICDeviceTypeMask;

pub use self::__ICDevice::ICEnumerationChronologicalOrder;

pub use self::__ICDevice::ICLocalizedStatusNotificationKey;

pub use self::__ICDevice::ICSessionOptions;

pub use self::__ICDevice::ICStatusCodeKey;

pub use self::__ICDevice::ICStatusNotificationKey;

pub use self::__ICDevice::ICTransportTypeBluetooth;

pub use self::__ICDevice::ICTransportTypeExFAT;

pub use self::__ICDevice::ICTransportTypeFireWire;

pub use self::__ICDevice::ICTransportTypeMassStorage;

pub use self::__ICDevice::ICTransportTypeProximity;

pub use self::__ICDevice::ICTransportTypeTCPIP;

pub use self::__ICDevice::ICTransportTypeUSB;

pub use self::__ICDeviceBrowser::ICAuthorizationStatus;

pub use self::__ICDeviceBrowser::ICAuthorizationStatusAuthorized;

pub use self::__ICDeviceBrowser::ICAuthorizationStatusDenied;

pub use self::__ICDeviceBrowser::ICAuthorizationStatusNotDetermined;

pub use self::__ICDeviceBrowser::ICAuthorizationStatusRestricted;

pub use self::__ICDeviceBrowser::ICDeviceBrowser;

pub use self::__ICDeviceBrowser::ICDeviceBrowserDelegate;

pub use self::__ICScannerBandData::ICScannerBandData;

pub use self::__ICScannerDevice::ICButtonTypeCopy;

pub use self::__ICScannerDevice::ICButtonTypeMail;

pub use self::__ICScannerDevice::ICButtonTypePrint;

pub use self::__ICScannerDevice::ICButtonTypeScan;

pub use self::__ICScannerDevice::ICButtonTypeTransfer;

pub use self::__ICScannerDevice::ICButtonTypeWeb;

pub use self::__ICScannerDevice::ICScannerDevice;

pub use self::__ICScannerDevice::ICScannerDeviceDelegate;

pub use self::__ICScannerDevice::ICScannerStatusRequestsOverviewScan;

pub use self::__ICScannerDevice::ICScannerStatusWarmUpDone;

pub use self::__ICScannerDevice::ICScannerStatusWarmingUp;

pub use self::__ICScannerDevice::ICScannerTransferMode;

pub use self::__ICScannerFunctionalUnits::ICScannerBitDepth;

pub use self::__ICScannerFunctionalUnits::ICScannerColorDataFormatType;

pub use self::__ICScannerFunctionalUnits::ICScannerDocumentType;

pub use self::__ICScannerFunctionalUnits::ICScannerFeature;

pub use self::__ICScannerFunctionalUnits::ICScannerFeatureBoolean;

pub use self::__ICScannerFunctionalUnits::ICScannerFeatureEnumeration;

pub use self::__ICScannerFunctionalUnits::ICScannerFeatureRange;

pub use self::__ICScannerFunctionalUnits::ICScannerFeatureTemplate;

pub use self::__ICScannerFunctionalUnits::ICScannerFeatureType;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnit;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitDocumentFeeder;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitFlatbed;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitNegativeTransparency;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitPositiveTransparency;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitState;

pub use self::__ICScannerFunctionalUnits::ICScannerFunctionalUnitType;

pub use self::__ICScannerFunctionalUnits::ICScannerMeasurementUnit;

pub use self::__ICScannerFunctionalUnits::ICScannerPixelDataType;

pub use self::__ImageCaptureConstants::ICEXIFOrientationType;

pub use self::__ImageCaptureConstants::ICErrorDomain;

pub use self::__ImageCaptureConstants::ICLegacyReturnCode;

pub use self::__ImageCaptureConstants::ICReturnCode;

pub use self::__ImageCaptureConstants::ICReturnCodeOffset;

pub use self::__ImageCaptureConstants::ICReturnConnectionErrorCode;

pub use self::__ImageCaptureConstants::ICReturnDownloadErrorCode;

pub use self::__ImageCaptureConstants::ICReturnMetadataErrorCode;

pub use self::__ImageCaptureConstants::ICReturnObjectErrorCode;

pub use self::__ImageCaptureConstants::ICReturnPTPDeviceErrorCode;

pub use self::__ImageCaptureConstants::ICReturnThumbnailErrorCode;

pub use self::__ImageCaptureConstants::ICRunLoopMode;
